inherit_from: base.yaml
experiment:
    num_train_workers: 12
    batch_size: 16
    experiment_name: can_on_cabinet_refine_pose_only_refine_rrp_1q_with_cropped_parent_nsm_arch_global_diff_steps_timestep_anneal_crop_interp_large_5_more_precise_sampling_rpdiff_edit
    meshcat_on: True
    resume: True
    num_iterations: 500000
    train:
        train_coarse_aff: False
        train_refine_pose: True
        train_success: False
        out_log_full: False
        out_log_coarse_aff: True
        out_log_refine_pose: True
        out_log_success: True
        
data:
    dataset_path: can_in_cabinet_stack/task_name_stack_can_in_cabinet_chunked  # set me to specify dataset folder
    parent_mesh_dir: syn_can_cabinet_obj_unnormalized
    child_mesh_dir: syns_can_obj
    load_full_pcd: False
    pose_perturb:
        use_small_rot_scale: False
        use_small_trans_scale: False
        rot_scale_deg: 360
        trans_scale: 0.48
    refine_pose:
        diffusion_steps: true
        n_diffusion_steps: 5
        vary_crop_size_diffusion: true
        interp_diffusion_traj: true
        precise_diff_prob: true
        aug:
            rot_aug: 

optimizer:
    refine_pose:
        type: AdamW
        valid_opts:
        - Adam
        - AdamW
        use_schedule: true
        schedule:
            fixed_lr: false
            min_lr: 1.0e-06
            warmup_epochs: 50
        opt_kwargs:
            AdamW:
                lr: 0.0001
                weight_decay: 1.0e-01
                betas:
                - 0.9
                - 0.95

model:
    coarse_aff:
        type: cnn
    refine_pose:
        type: nsm_transformer # transformer, tranfsormer_mq, pointnet, cnn    
        model_kwargs:
            nsm_transformer:
                n_queries: 1
                use_timestep_emb: True
                max_timestep: 5
                timestep_pool_method: meanpool  # meanpool, concat

loss:
    refine_pose:
        type: tf_chamfer
    tf_chamfer:
        l1: True
